/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Banco.ConexaoMySQL;
import Banco.Consultas;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Anderson Tonon
 */
public class Cadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form teste
     */
    public Cadastro() {
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); 
        cadastro.setBorder(null);
        
        
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        campoPdv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoSuprimentos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoVendaPrazo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoPos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoTef = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoSaldo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoRecebimentos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoSangria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoVendaReceb = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        setForeground(new java.awt.Color(51, 51, 51));
        setIconifiable(true);
        setResizable(true);
        setTitle("Ajuda");
        setEnabled(false);
        setFocusCycleRoot(false);
        setVisible(true);

        cadastro.setBackground(new java.awt.Color(153, 153, 153));
        cadastro.setPreferredSize(new java.awt.Dimension(882, 657));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Nome:");

        campoNome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoNome.setForeground(new java.awt.Color(102, 102, 102));
        campoNome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Magda", "Dayse", "Claudia", "Camila" }));
        campoNome.setBorder(null);
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("PDV:");

        campoPdv.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoPdv.setForeground(new java.awt.Color(102, 102, 102));
        campoPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPdvActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("Suprimentos:");

        campoSuprimentos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoSuprimentos.setForeground(new java.awt.Color(102, 102, 102));
        campoSuprimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSuprimentosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Vendas a Prazo:");

        campoVendaPrazo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoVendaPrazo.setForeground(new java.awt.Color(102, 102, 102));
        campoVendaPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoVendaPrazoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("P.O.S:");

        campoPos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoPos.setForeground(new java.awt.Color(102, 102, 102));
        campoPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("Tef:");

        campoTef.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoTef.setForeground(new java.awt.Color(102, 102, 102));
        campoTef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTefActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("Saldo:");

        campoSaldo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoSaldo.setForeground(new java.awt.Color(102, 102, 102));
        campoSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSaldoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("Recebimentos:");

        campoRecebimentos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoRecebimentos.setForeground(new java.awt.Color(102, 102, 102));
        campoRecebimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRecebimentosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("Sangria:");

        campoSangria.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoSangria.setForeground(new java.awt.Color(102, 102, 102));
        campoSangria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSangriaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel3.setText("Venda e Recebimentos:");

        campoVendaReceb.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoVendaReceb.setForeground(new java.awt.Color(102, 102, 102));
        campoVendaReceb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoVendaRecebActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));

        jLabel10.setBackground(new java.awt.Color(153, 0, 0));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("LANÇAMENTOS DE CAIXA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton6.setText("Salvar");
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton8.setText("Limpar");
        jButton8.setBorder(null);
        jButton8.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        message.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout cadastroLayout = new javax.swing.GroupLayout(cadastro);
        cadastro.setLayout(cadastroLayout);
        cadastroLayout.setHorizontalGroup(
            cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroLayout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadastroLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(cadastroLayout.createSequentialGroup()
                            .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46)
                            .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoNome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoSuprimentos)
                                .addComponent(campoVendaPrazo)
                                .addComponent(campoPos)
                                .addComponent(campoPdv)
                                .addComponent(campoTef, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                    .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campoSangria)
                        .addComponent(campoVendaReceb)
                        .addComponent(campoRecebimentos)
                        .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadastroLayout.setVerticalGroup(
            cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroLayout.createSequentialGroup()
                .addContainerGap(565, Short.MAX_VALUE)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadastroLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(61, 61, 61)
                    .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(campoVendaReceb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoPdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8)
                        .addComponent(campoSangria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(campoSuprimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoRecebimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGap(25, 25, 25)
                    .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(campoVendaPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(campoPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(campoTef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addGap(68, 68, 68)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPdvActionPerformed

    private void campoSuprimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSuprimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSuprimentosActionPerformed

    private void campoVendaPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoVendaPrazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoVendaPrazoActionPerformed

    private void campoPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPosActionPerformed

    private void campoTefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTefActionPerformed

    private void campoSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSaldoActionPerformed

    private void campoRecebimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRecebimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRecebimentosActionPerformed

    private void campoSangriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSangriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSangriaActionPerformed

    private void campoVendaRecebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoVendaRecebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoVendaRecebActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        try {
            cadastrarLancamento();
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton8ActionPerformed
    private void limparCampos(){
        campoNome.setSelectedIndex(0);
        campoPdv.setText("");
        campoSuprimentos.setText("");
        campoVendaPrazo.setText("");
        campoPos.setText("");
        campoTef.setText("");
        campoVendaReceb.setText("");
        campoSangria.setText("");
        campoRecebimentos.setText("");
        campoSaldo.setText("");
    }
    private boolean verificarCampos(){
        
        message.setForeground(new Color(170,0,0));
        
        if(campoNome.getSelectedIndex() < 1){
            message.setText("Preencha o campo Nome!!!");
            return false;
        }   
        if(campoPdv.getText().length() < 1){
            message.setText("Preencha o campo PDV!!!");  
            return false;
        }       
        if(campoSuprimentos.getText().length() < 1){
            message.setText("Preencha o campo Suprimentos!!!");  
            return false;
        }   
        if(campoVendaPrazo.getText().length() < 1){
            message.setText("Preencha o campo Venda a Prazo!!!");  
            return false;
        }   
        if(campoPos.getText().length() < 1){
            message.setText("Preencha o campo P.O.S!!!");  
            return false;
        }   
        if(campoPdv.getText().length() < 1){
            System.out.println("Preencha o campo PDV!!!");  
            return false;
        }   
        if(campoTef.getText().length() < 1){
            message.setText("Preencha o campo Tef!!!");  
            return false;
        }     
        if(campoVendaReceb.getText().length() < 1){
            message.setText("Preencha o campo Venda e Recebimentos!!!"); 
            return false;
        }   
        if(campoSangria.getText().length() < 1){
            message.setText("Preencha o campo Sangria!!!");
            return false;
        }   
        if(campoRecebimentos.getText().length() < 1){
            message.setText("Preencha o campo Recebimentos!!!");
             return false;
        }    
        if(campoSaldo.getText().length() < 1){
            message.setText("Preencha o campo Saldo!!!");
            return false;
        }   
        
        return true;
    }
    
    private void cadastrarLancamento() throws SQLException{
        
        ConexaoMySQL sql = new ConexaoMySQL();
        String dados[] = new String[11]; 
        
        LocalDate localDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String data = localDate.format(formatter);
        
        if(verificarCampos()){
            dados[0] = (String) campoNome.getSelectedItem();
            dados[1] = campoPdv.getText();
            dados[2] = campoSuprimentos.getText();
            dados[3] = campoVendaPrazo.getText();
            dados[4] = campoPos.getText();
            dados[5] = campoTef.getText();
            dados[6] = campoVendaReceb.getText();
            dados[7] = campoSangria.getText();
            dados[8] = campoRecebimentos.getText();
            dados[9] = campoSaldo.getText();
            dados[10] = data;

            boolean status = sql.CadastrarLancamento(Consultas.CADASTRO_LANCAMENTO, dados);

            if(status){
                message.setForeground(Color.green);
                message.setText("Lançamento cadastrado!!!");
                limparCampos();
            }else{
                message.setForeground(Color.red);
                message.setText("Ocorreu um erro inesperado!!");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cadastro;
    private javax.swing.JComboBox<String> campoNome;
    private javax.swing.JTextField campoPdv;
    private javax.swing.JTextField campoPos;
    private javax.swing.JTextField campoRecebimentos;
    private javax.swing.JTextField campoSaldo;
    private javax.swing.JTextField campoSangria;
    private javax.swing.JTextField campoSuprimentos;
    private javax.swing.JTextField campoTef;
    private javax.swing.JTextField campoVendaPrazo;
    private javax.swing.JTextField campoVendaReceb;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
