/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Banco.ConexaoMySQL;
import Banco.Consultas;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Anderson Tonon
 */
public class Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form teste
     */
    public Usuario() {
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); 
        cadastro.setBorder(null);
        
        
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastro = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNome2 = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        campoNome3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        editar = new javax.swing.JToggleButton();
        message = new javax.swing.JLabel();
        message1 = new javax.swing.JLabel();
        campoIdUse = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        setForeground(new java.awt.Color(51, 51, 51));
        setIconifiable(true);
        setResizable(true);
        setTitle("Ajuda");
        setEnabled(false);
        setFocusCycleRoot(false);
        setVisible(true);

        cadastro.setBackground(new java.awt.Color(153, 153, 153));

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));

        jLabel10.setBackground(new java.awt.Color(153, 0, 0));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("USUÁRIOS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        campoLogin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoLogin.setForeground(new java.awt.Color(0, 0, 0));
        campoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoLogin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Login:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Senha:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("Buscar");

        campoNome2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoNome2.setForeground(new java.awt.Color(102, 102, 102));
        campoNome2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoNome2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        campoNome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNome2MouseClicked(evt);
            }
        });
        campoNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNome2ActionPerformed(evt);
            }
        });

        campoSenha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoSenha.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Nome:");

        campoNome3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoNome3.setForeground(new java.awt.Color(0, 0, 0));
        campoNome3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoNome3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setMnemonic('1');
        jButton1.setText("Excluir");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setMnemonic('1');
        jButton2.setText("Salvar");
        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setMnemonic('1');
        jButton3.setText("Buscar");
        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        editar.setForeground(new java.awt.Color(51, 51, 51));
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        message.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        message.setForeground(new java.awt.Color(0, 0, 0));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        message1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        message1.setForeground(new java.awt.Color(0, 0, 0));
        message1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        campoIdUse.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoIdUse.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Id:");

        javax.swing.GroupLayout cadastroLayout = new javax.swing.GroupLayout(cadastro);
        cadastro.setLayout(cadastroLayout);
        cadastroLayout.setHorizontalGroup(
            cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cadastroLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(58, 58, 58)
                        .addComponent(campoNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(message1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(43, 43, 43)
                        .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoNome3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(campoLogin))
                            .addComponent(campoSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoIdUse, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );
        cadastroLayout.setVerticalGroup(
            cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoIdUse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(67, 67, 67)
                                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(cadastroLayout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        message.setText("");
        message1.setText("");
            
            if(campoIdUse.getText().length() > 0 ){
               
                int idUser = Integer.parseInt(campoIdUse.getText());
            
            try {
                if(!excluirUsuario(idUser)){
                    
                    message.setText("Usuário excluido!!!");
                    message.setForeground(Color.green);
                }else{
                    message.setText("Error !!!");
                    message.setForeground(Color.red);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        message.setText("");
        message1.setText("");
        
        if(campoIdUse.getText().length() > 0){
            try {
                editarUsuario(campoIdUse.getText(), campoLogin.getText(), campoNome3.getText(), campoSenha.getText());
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                if(campoLogin.getText().length() > 0 && campoNome3.getText().length() > 0 && campoSenha.getText().length() > 0){
                    cadastrarUsuario(campoLogin.getText(), campoNome3.getText(), campoSenha.getText());
                }else{
                    message.setText("Verifique os dados!!!");
                }

            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        campoSenha.setText("");
        campoIdUse.setText("");
        campoNome3.setText("");
        campoLogin.setText("");
        message.setText("");
        message1.setText("");
        try {
            buscarUsuario(campoNome2.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        message.setText("");
        message1.setText("");
        if(editar.isSelected()){
            campoLogin.setEditable(true);
            campoNome3.setEditable(true);
            campoSenha.setEditable(true);
            
            campoLogin.setBackground(Color.WHITE);
            campoNome3.setBackground(Color.WHITE);
            campoSenha.setBackground(Color.WHITE);
        }else{
            campoLogin.setEditable(false);
            campoNome3.setEditable(false);
            campoSenha.setEditable(false);
            
            campoLogin.setBackground(new Color(153,153,153));
            campoNome3.setBackground(new Color(153,153,153));
            campoSenha.setBackground(new Color(153,153,153));
        }
    }//GEN-LAST:event_editarActionPerformed

    private void campoNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNome2ActionPerformed
        message1.setText("");
    }//GEN-LAST:event_campoNome2ActionPerformed

    private void campoNome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNome2MouseClicked
        message1.setText("");
    }//GEN-LAST:event_campoNome2MouseClicked
    public void buscarUsuario(String usuario) throws SQLException{
        
        ConexaoMySQL sql = new ConexaoMySQL();  
        String[] user = sql.buscarUsuario(Consultas.BUSCA_USER, usuario);
        
        if(campoNome2.getText().length() < 2){
            message1.setText("Digite um nome de Usuário!!!");
            
        }else if(user != null){
            message1.setText("Usuário encontrado!!!");
            message1.setForeground(Color.green);
            campoIdUse.setText(user[0]);
            campoLogin.setText(user[1]);
            campoNome3.setText(user[2]);
            campoSenha.setText(user[3]);

            campoLogin.setEditable(false);
            campoNome3.setEditable(false);
            campoSenha.setEditable(false);
            
            campoLogin.setBackground(new Color(153,153,153));
            campoNome3.setBackground(new Color(153,153,153));
            campoSenha.setBackground(new Color(153,153,153));

            editar.setSelected(false);
        }else{
            message1.setText("Usuário não encontrado!!!");
            message1.setForeground(Color.red);
        }
        
    }
    private boolean excluirUsuario(int idUser) throws SQLException{
        ConexaoMySQL sql = new ConexaoMySQL();  
        boolean status = sql.removerUser(Consultas.REMOVE_USER, idUser);
        
        message.setText("Usuário cadastrado!!!");
        message.setForeground(new Color(0,204,51));
        limparCampos();
        
        return status;
    }
    
    private boolean editarUsuario(String idUser, String user, String nomeUser, String senhaUser) throws SQLException{
        ConexaoMySQL sql = new ConexaoMySQL();  
        boolean status = sql.editarUser(Consultas.EDITAR_USER, user, nomeUser, senhaUser, idUser);
        message.setText("Usuário modificado!!!");
        message.setForeground(new Color(0,204,51));
        return status;
    }
    
    private boolean cadastrarUsuario(String user, String nomeUser, String senhaUser) throws SQLException{
        ConexaoMySQL sql = new ConexaoMySQL();  
        boolean status = sql.cadastrarUser(Consultas.CADASTRO_USER, user, nomeUser, senhaUser);
        message.setText("Usuário cadastrado!!!");
        message.setForeground(new Color(0,204,51));
        return status;
    }
    private void limparCampos(){
        campoIdUse.setText("");
        campoLogin.setText("");
        campoNome3.setText("");
        campoSenha.setText("");
    }
    
    
    ConexaoMySQL sql = new ConexaoMySQL();  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cadastro;
    private javax.swing.JLabel campoIdUse;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome2;
    private javax.swing.JTextField campoNome3;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JToggleButton editar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel message1;
    // End of variables declaration//GEN-END:variables
}
